# Packages --------------------------------------------------------------------

einer:
  alpha: 'einer-2.0.0-alpha.2'
  beta: 'einer-2.0.0-beta.1'
  release: 'einer-2.0.1'

# DCCs (Autodesk Maya) --------------------------------------------------------

maya:
  '2020': 'maya-2020.4.0'
  '2019': 'maya-2019.3.1'
